version: "3"
services:
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5433:5432"

  bonus_service:
    container_name: bonus_service
    build:
      context: src
      dockerfile: BonusService/Dockerfile
    depends_on:
      - postgres
    ports:
      - "8050:8050"
  
  flight_service:
    container_name: flight_service
    build:
      context: src
      dockerfile: FlightService/Dockerfile
    depends_on:
      - postgres
    ports:
      - "8060:8060"
  
  ticket_service:
    container_name: ticket_service
    build:
      context: src
      dockerfile: TicketService/Dockerfile
    depends_on:
      - postgres
    ports:
      - "8070:8070"
  
  gateway_service:
    container_name: gateway_service
    build:
      context: src
      dockerfile: GatewayService/Dockerfile
    depends_on:
      - postgres
    ports:
      - "8080:8080"

volumes:
  db-data:
  