name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Install dependencies
        run: |
          dotnet restore ./src/BonusService/BonusService.csproj
          dotnet restore ./src/FlightService/FlightService.csproj
          dotnet restore ./src/TicketService/TicketService.csproj
          dotnet restore ./src/GatewayService/GatewayService.csproj

      - name: Build
        run: |
          dotnet publish ./src/BonusService/BonusService.csproj -c Release
          dotnet publish ./src/FlightService/FlightService.csproj -c Release
          dotnet publish ./src/TicketService/TicketService.csproj -c Release
          dotnet publish ./src/GatewayService/GatewayService.csproj -c Release

      - name: Run Tests
        run: dotnet test ./src

      - name: Build images
        timeout-minutes: 10
        run: docker compose build

      - name: Run containers
        timeout-minutes: 5
        run: |
          docker compose up -d
          ./scripts/wait-script.sh
        env:
          WAIT_PORTS: 8080,8070,8060,8050

      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: v1/postman/collection.json
          environment: v1/postman/environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'

      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true

      - name: Stop containers
        if: always()
        continue-on-error: true
        run: docker compose down -v